### ISSUE TITLE
Blog post Improvement suggestions

### ISSUE THREAD

**Issue by shivaylamba** [advantch/django-htmx#2]
1. Wrong link in the blog post for the Meilisearch demo: 
in the blog, the GitHub  link mentioned that redirects to the main branch instead of htmx-meilisearch So, so the correct link should be https://github.com/advantch/django-htmx/tree/htmx-meilisearch

2. Can the M in meilisearch be capital?
<img width="689" alt="image" src="https://user-images.githubusercontent.com/19529592/169271506-dfba53ac-bc08-4a29-b33d-ff9a0a39252c.png">

@Thembahank

**Comment by Thembahank** [comment]
@shivaylamba You are a god send, thank you. 🙏🏼  Fixed this.

**Comment by shivaylamba** [comment]
Thank you @Thembahank
