### ISSUE TITLE
make seed_db command is throwing error

### ISSUE THREAD

**Issue by shivaylamba** [advantch/django-htmx#3]
`make seed_db `command throws this error: `FileNotFoundError: [Errno 2] No such file or directory`

Suggestion: I think you should move this file: `apps/mybnb/management/commands/json_data.json` to the root directory

**Comment by shivaylamba** [comment]
@Thembahank

**Comment by shivaylamba** [comment]
@Thembahank can you also look into this issue, if possible?

**Comment by Thembahank** [comment]
@shivaylamba  this should be sorted as well. Update this and the readme instructions. Please reopen if you are still facing issues.
